exp_name: ~
model_type: BaselineModel
log_dir: ./tb_logger
save_dir: ../exps
device: cuda
multi_gpu: false

datasets:
  train_dataset:
    type: SimpleCSVDataloader
    dataroot: /path/to/your/dataset
    csv_path: /path/to/your/train.csv
    imgpath_colname: 'image_path'
    label_colname: 'label'
    is_append_root: true
    augment:
      augment_type: flip_aug
      size: 512
    batch_size: 10
    num_workers: 4

  val_dataset:
    type: SimpleCSVDataloader
    dataroot: /path/to/your/dataset
    csv_path: /path/to/your/val.csv
    imgpath_colname: 'image_path'
    label_colname: 'label'
    is_append_root: true
    augment:
      augment_type: flip_aug
      size: 512


train:
  num_epoch: 100
  model_arch:
    type: TimmArch
    load_path: ~
    backbone: resnet34
    num_classes: 3
    pretrained: false

  optimizer:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [80]
    gamma: 0.1

  criterion:
    type: celoss

  metric:
    type: topk_acc
    k: 1

eval:
  eval_interval: 2
